project:
  type: website
  output-dir: docs

website:
  title: "Clara's R Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/creyes-5/rcc_blog_reyes
      - icon: linkedin
        href: https://linkedin.com/in/clara-rey-es/

format:
  html:
    theme: lumen
    css: styles.css

editor: visual

