project:
  type: website
  output-dir: docs

website:
  title: "Clara's R Portfolio"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/creyes-5/rcc_blog_reyes
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: lumen
    css: styles.css

editor: visual

